[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Set warning configurations
ignore_warnings = true
 remappings = [
    "solady/=lib/solady/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[invariant]
runs = 256
depth = 64
fail_on_revert = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
